### ISSUE TITLE
Error creating project

### ISSUE THREAD

**Issue by dev-vickie** [backframe/backframe.js#212]
Trying to create a new project using the $npx @backframe/create-bf  command says that it's not in the registry. Did i miss something?

![image](https://user-images.githubusercontent.com/56781148/233536369-5b2ff41c-f02b-4f0a-924c-50d4fc5519d0.png)

**Comment by ndaba1** [comment]
Backframe is still in private alpha and as such, it is hosted on a private npm registry on github. You will need certain access tokens to be able to use it. I would be more than happy to give you said tokens. Hit me up https://t.me/vndaba
